const { test, expect } = require('@playwright/test');

// Define the base URL for the E2E environment
const BASE_URL = 'http://localhost:3000';

test.describe('NodeJS Shopping Cart E2E Tests', () => {

  test('Add item to cart and verify cart view', async ({ page }) => {
    // Navigate to the catalog to trigger product selection
    await page.goto(`${BASE_URL}/`);
    
    // Simulate user intent: add the first available item to the session
    // We use an attribute selector matching the href generated by the template
    await page.click('a[href^="/add/"] >> nth=0'); 
    
    await page.goto(`${BASE_URL}/cart`);
    
    // Validate that the session state correctly propagates to the UI
    // Checking for the list-group-item class defined in cart.hbs
    const cartItem = page.locator('.list-group-item');
    await expect(cartItem).toBeVisible();
    await expect(cartItem).toContainText('CHF');
  });

  test('Remove item from cart', async ({ page }) => {
    await page.goto(`${BASE_URL}/`);
    await page.click('a[href^="/add/"] >> nth=0');
    
    await page.goto(`${BASE_URL}/cart`);
    
    // Ensure the removal route correctly mutates the session state 
    // by targeting the specific button class
    await page.click('.btn-default:has-text("Remove")');
    
    // Confirm the UI gracefully handles the transition back to an empty state
    await expect(page.locator('body')).toContainText('Your shopping cart is empty.');
  });

  test('Session persistence across reloads', async ({ page }) => {
    await page.goto(`${BASE_URL}/`);
    await page.click('a[href^="/add/"] >> nth=0');
    
    // Force a page reload to verify that the Express session middleware 
    // persists the cart data correctly in the server-side session
    await page.reload();
    
    await page.goto(`${BASE_URL}/cart`);
    
    await expect(page.locator('.list-group-item')).toBeVisible();
  });

  test('Empty cart navigation logic', async ({ page }) => {
    // Verify that the application logic handles uninitialized sessions 
    // without triggering runtime errors when accessing the cart route
    await page.goto(`${BASE_URL}/cart`);
    
    // Validate the home link redirection to ensure correct circular navigation
    await page.goto(`${BASE_URL}/`);
    
    await expect(page).toHaveURL(/.*\//);
  });
});
